version: '3.8'

services:
  cesizen_db:
    container_name: cesizen_db
    image: mariadb:latest
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: bddname
      MARIADB_USER: roger
      MARIADB_PASSWORD: regor
    healthcheck:
      test: ['CMD', '/usr/local/bin/healthcheck.sh', '--innodb_initialized']
      start_period: 5s
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  cesizen_app:
    container_name: cesizen_app
    image: ghcr.io/louislucas64/cesizen:latest
    environment:
      BDD_HOST: cesizen_db
    ports:
      - "12000:12000"
    depends_on:
      cesizen_db:
        condition: service_healthy
    restart: unless-stopped