name: 01-3 - Integration - SNYK

on:
  workflow_call

jobs:
  Security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install Snyk CLI
        run: |
          curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x snyk
          sudo mv snyk /usr/local/bin

      - name: Run Snyk test on all projects via solution file
        run: snyk test --file=CESIZenAppli.sln --severity-threshold=medium
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Monitor the solution
        run: snyk monitor --file=CESIZenAppli.sln
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}