name: 02-2 - Delivery - Trivy Scan

on:
  workflow_call

env:
  REGISTRY: ghcr.io
  USERNAME: ${{ github.actor }}
  IMAGE_NAME: ${{ github.repository }} # orga/repo

jobs:
  Trivy_Scan_Monolith:
    runs-on: ubuntu-20.04

    steps:
      - name: Registry Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.MONOREPO_PAT }}

      - name: Downcase Image Name
        run: echo "IMAGE_NAME_LOWER=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Trivy Monolith vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:canary
          format: 'table'
          exit-code: '1'
          output: 'monolith-trivy-results.txt'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Upload Trivy results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: monolith-trivy-results
          path: monolith-trivy-results.txt
          retention-days: 1
