name: 02-1 - Delivery - Docker GHCR

on:
  workflow_call:
    inputs:
      docker-mode:
        required: false
        type: string
        default: latest

env:
  REGISTRY: ghcr.io
  USERNAME: ${{ github.actor }}
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Build-Push-DockerGhcr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Registry Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.MONOREPO_PAT }}

      - name: Downcase Image Name
        run: echo "IMAGE_NAME_LOWER=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Build Monolith Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:${{ inputs.docker-mode }}

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          version: 'v0.64.1'

      - name: Scan image with Trivy (CLI)
        run: |
          trivy image --exit-code 1 \
            --severity CRITICAL,HIGH,MEDIUM \
            --ignore-unfixed \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:${{ inputs.docker-mode }}

      - name: Push Monolith Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:${{ inputs.docker-mode }}

      - name: Print
        run: env | sort